"""empty message

Revision ID: 1c6fb0f47bd1
Revises: a847547e3cde
Create Date: 2019-10-09 09:59:29.199058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c6fb0f47bd1'
down_revision = 'a847547e3cde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('nb_street', sa.String(length=10), nullable=True),
    sa.Column('street', sa.String(length=250), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('zip', sa.String(length=60), nullable=True),
    sa.Column('nb_child', sa.Integer(), nullable=True),
    sa.Column('marital_status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['manager.manager_id'], ),
    sa.PrimaryKeyConstraint('id', 'client_id'),
    sa.UniqueConstraint('client_id')
    )
    op.create_foreign_key(None, 'admin', 'user', ['id'], ['id'])
    op.create_foreign_key(None, 'manager', 'user', ['id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'manager', type_='foreignkey')
    op.drop_constraint(None, 'admin', type_='foreignkey')
    op.drop_table('client')
    # ### end Alembic commands ###
