"""empty message

Revision ID: 2bde37ee1773
Revises: 
Create Date: 2019-10-10 10:55:58.138213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bde37ee1773'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_number', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('CURRENT_ACCOUNT', 'DEBIT_ACCOUNT', 'PAID_ACCOUNT', name='typeaccount'), server_default='CURRENT_ACCOUNT', nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('iban', sa.String(length=20), nullable=True),
    sa.Column('balance', sa.Float(precision=12, asdecimal=2), nullable=True),
    sa.Column('cashier_facility', sa.Float(precision=12, asdecimal=2), nullable=True),
    sa.Column('benefit', sa.Float(precision=12, asdecimal=2), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('iban')
    )
    op.create_index(op.f('ix_account_account_number'), 'account', ['account_number'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lastname', sa.String(length=64), nullable=True),
    sa.Column('firstname', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_user_firstname'), 'user', ['firstname'], unique=False)
    op.create_index(op.f('ix_user_lastname'), 'user', ['lastname'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id', 'admin_id'),
    sa.UniqueConstraint('admin_id')
    )
    op.create_table('manager',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=False),
    sa.Column('mle', sa.Integer(), nullable=True),
    sa.Column('entry_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id', 'manager_id'),
    sa.UniqueConstraint('manager_id')
    )
    op.create_foreign_key(None, 'client', 'manager', ['manager_id'], ['manager_id'])
    op.create_foreign_key(None, 'client', 'user', ['id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'client', type_='foreignkey')
    op.drop_constraint(None, 'client', type_='foreignkey')
    op.drop_table('manager')
    op.drop_table('admin')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_lastname'), table_name='user')
    op.drop_index(op.f('ix_user_firstname'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_account_account_number'), table_name='account')
    op.drop_table('account')
    # ### end Alembic commands ###
