"""empty message

Revision ID: 2c90a235bd02
Revises: 83433df227d5
Create Date: 2019-10-10 11:17:17.042502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c90a235bd02'
down_revision = '83433df227d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'admin', 'user', ['id'], ['id'])
    op.create_foreign_key(None, 'client', 'manager', ['manager_id'], ['manager_id'])
    op.create_foreign_key(None, 'client', 'user', ['id'], ['id'])
    op.create_foreign_key(None, 'manager', 'user', ['id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'manager', type_='foreignkey')
    op.drop_constraint(None, 'client', type_='foreignkey')
    op.drop_constraint(None, 'client', type_='foreignkey')
    op.drop_constraint(None, 'admin', type_='foreignkey')
    # ### end Alembic commands ###
