"""update polymorphism + transaction history table

Revision ID: 5c976fee56a6
Revises: b8f9b00227d9
Create Date: 2019-10-12 13:17:37.974545

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5c976fee56a6'
down_revision = 'b8f9b00227d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paid_account_benefit_history', sa.Column('balance_attime', sa.Float(precision=12, asdecimal=2), nullable=True))
    op.drop_column('paid_account_benefit_history', 'balance_daily')
    op.add_column('transaction_history', sa.Column('balance_before_transaction', sa.Float(precision=12, asdecimal=2), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction_history', 'balance_before_transaction')
    op.add_column('paid_account_benefit_history', sa.Column('balance_daily', mysql.FLOAT(), nullable=True))
    op.drop_column('paid_account_benefit_history', 'balance_attime')
    # ### end Alembic commands ###
