"""empty message

Revision ID: 83433df227d5
Revises: 2bde37ee1773
Create Date: 2019-10-10 11:06:52.105926

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '83433df227d5'
down_revision = '2bde37ee1773'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('nb_street', sa.String(length=10), nullable=True),
    sa.Column('street', sa.String(length=250), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('zip', sa.String(length=60), nullable=True),
    sa.Column('nb_child', sa.Integer(), nullable=True),
    sa.Column('marital_status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['manager.manager_id'], ),
    sa.PrimaryKeyConstraint('id', 'client_id'),
    sa.UniqueConstraint('client_id')
    )
    op.drop_index('admin_id', table_name='admin')
    op.create_foreign_key(None, 'admin', 'user', ['id'], ['id'])
    op.drop_column('admin', 'admin_id')
    op.create_foreign_key(None, 'manager', 'user', ['id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'manager', type_='foreignkey')
    op.add_column('admin', sa.Column('admin_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'admin', type_='foreignkey')
    op.create_index('admin_id', 'admin', ['admin_id'], unique=True)
    op.drop_table('client')
    # ### end Alembic commands ###
