"""empty message

Revision ID: 9047ad576493
Revises: 
Create Date: 2019-10-10 02:15:03.220064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9047ad576493'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_number', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('CURRENT_ACCOUNT', 'DEBIT_ACCOUNT', 'PAID_ACCOUNT', name='typeaccount'), server_default='CURRENT_ACCOUNT', nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('iban', sa.String(length=20), nullable=True),
    sa.Column('balance', sa.Float(precision=12, asdecimal=2), nullable=True),
    sa.Column('cashier_facility', sa.Float(precision=12, asdecimal=2), nullable=True),
    sa.Column('benefit', sa.Float(precision=12, asdecimal=2), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('iban')
    )
    op.create_index(op.f('ix_account_account_number'), 'account', ['account_number'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_account_account_number'), table_name='account')
    op.drop_table('account')
    # ### end Alembic commands ###
