"""empty message

Revision ID: bfa4d884a084
Revises: 7cf02edf3f58
Create Date: 2019-10-11 14:52:51.754964

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bfa4d884a084'
down_revision = '7cf02edf3f58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'account', 'client', ['client_id'], ['id'])
    op.create_foreign_key(None, 'admin', 'user', ['id'], ['id'])
    op.create_foreign_key(None, 'client', 'user', ['id'], ['id'])
    op.create_foreign_key(None, 'client', 'manager', ['manager_id'], ['id'])
    op.create_foreign_key(None, 'debit_account_agios_history', 'account', ['account_id'], ['id'])
    op.create_foreign_key(None, 'manager', 'user', ['id'], ['id'])
    op.add_column('open_account_request', sa.Column('email', sa.String(length=128), nullable=False))
    op.add_column('open_account_request', sa.Column('firstname', sa.String(length=64), nullable=False))
    op.add_column('open_account_request', sa.Column('id_card', sa.LargeBinary(), nullable=False))
    op.add_column('open_account_request', sa.Column('lastname', sa.String(length=64), nullable=False))
    op.add_column('open_account_request', sa.Column('phone', sa.String(length=20), nullable=False))
    op.add_column('open_account_request', sa.Column('proof_of_address', sa.LargeBinary(), nullable=False))
    op.add_column('open_account_request', sa.Column('salary', sa.LargeBinary(), nullable=False))
    op.add_column('open_account_request', sa.Column('username', sa.String(length=64), nullable=False))
    op.create_unique_constraint(None, 'open_account_request', ['username'])
    op.create_unique_constraint(None, 'open_account_request', ['email'])
    op.drop_column('open_account_request', 'request_data')
    op.create_foreign_key(None, 'paid_account_benefit_history', 'account', ['account_id'], ['id'])
    op.create_foreign_key(None, 'transaction_history', 'account', ['account_id'], ['id'])
    op.create_foreign_key(None, 'user_pwd', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_pwd', type_='foreignkey')
    op.drop_constraint(None, 'transaction_history', type_='foreignkey')
    op.drop_constraint(None, 'paid_account_benefit_history', type_='foreignkey')
    op.add_column('open_account_request', sa.Column('request_data', mysql.TEXT(), nullable=True))
    op.drop_constraint(None, 'open_account_request', type_='unique')
    op.drop_constraint(None, 'open_account_request', type_='unique')
    op.drop_column('open_account_request', 'username')
    op.drop_column('open_account_request', 'salary')
    op.drop_column('open_account_request', 'proof_of_address')
    op.drop_column('open_account_request', 'phone')
    op.drop_column('open_account_request', 'lastname')
    op.drop_column('open_account_request', 'id_card')
    op.drop_column('open_account_request', 'firstname')
    op.drop_column('open_account_request', 'email')
    op.drop_constraint(None, 'manager', type_='foreignkey')
    op.drop_constraint(None, 'debit_account_agios_history', type_='foreignkey')
    op.drop_constraint(None, 'client', type_='foreignkey')
    op.drop_constraint(None, 'client', type_='foreignkey')
    op.drop_constraint(None, 'admin', type_='foreignkey')
    op.drop_constraint(None, 'account', type_='foreignkey')
    # ### end Alembic commands ###
