"""Update account with client_id

Revision ID: da6310ea6d09
Revises: 048ad75417b2
Create Date: 2019-10-10 12:26:10.043558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da6310ea6d09'
down_revision = '048ad75417b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('client_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_account_client_id'), 'account', ['client_id'], unique=False)
    op.create_foreign_key(None, 'account', 'client', ['client_id'], ['id'])
    op.create_foreign_key(None, 'admin', 'user', ['id'], ['id'])
    op.create_foreign_key(None, 'client', 'manager', ['manager_id'], ['manager_id'])
    op.create_foreign_key(None, 'client', 'user', ['id'], ['id'])
    op.create_foreign_key(None, 'debit_account_agios_history', 'account', ['account_id'], ['id'])
    op.create_foreign_key(None, 'manager', 'user', ['id'], ['id'])
    op.create_foreign_key(None, 'paid_account_benefit_history', 'account', ['account_id'], ['id'])
    op.create_foreign_key(None, 'transaction_history', 'account', ['account_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transaction_history', type_='foreignkey')
    op.drop_constraint(None, 'paid_account_benefit_history', type_='foreignkey')
    op.drop_constraint(None, 'manager', type_='foreignkey')
    op.drop_constraint(None, 'debit_account_agios_history', type_='foreignkey')
    op.drop_constraint(None, 'client', type_='foreignkey')
    op.drop_constraint(None, 'client', type_='foreignkey')
    op.drop_constraint(None, 'admin', type_='foreignkey')
    op.drop_constraint(None, 'account', type_='foreignkey')
    op.drop_index(op.f('ix_account_client_id'), table_name='account')
    op.drop_column('account', 'client_id')
    # ### end Alembic commands ###
